jobs:
  abuse-monitor:
    name: With latest code base
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: comvent
      name: Handle with Comvent
      uses: rytswd/comvent@v0.3
      with:
        config-path: .github/config/comvent-ad.yaml
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: steps.comvent.outputs.blocked-words != ''
      name: Handle some abusive content
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "github.issues.deleteComment({\n  owner: context.repo.owner,\n  repo:\
          \ context.repo.repo,\n  comment_id: ${{ github.event.comment.id }}\n})\n\
          const comment = `Found blocked words! \U0001F630\nThe comment was thus removed.`;\n\
          github.issues.createComment({\n  issue_number: context.issue.number,\n \
          \ owner: context.repo.owner,\n  repo: context.repo.repo,\n  body: comment\n\
          })\n"
name: Monitor Abusive Comments
on:
  repository_dispatch:
    types: trigger-ga___monitor-abusive.yml
