jobs:
  noResponse:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: lee-dohm/no-response@v0.5.0
      with:
        token: ${{ github.token }}
name: No Response
on:
  repository_dispatch:
    types: trigger-ga___no-response.yml
permissions:
  issues: write
