jobs:
  greet:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      if: ${{ github.event_name == 'push'}}
      name: Set LD_VERSION
      run: echo "LD_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - continue-on-error: true
      if: ${{ github.event_name == 'workflow_dispatch'}}
      name: Set LD_VERSION
      run: echo "LD_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
    - continue-on-error: true
      name: Set PUBLISH_TOKEN
      run: echo "PUBLISH_TOKEN=${{ secrets.PUBLISH_TOKEN }}" >> $GITHUB_ENV
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      env:
        LD_VERSION: ${{ env.LD_VERSION }}
        PUBLISH_TOKEN: ${{ env.PUBLISH_TOKEN }}
      name: Build the plugin
      run: ./gradlew publishPlugin
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create_release
      name: Create Release
      uses: actions/create-release@v1
      with:
        draft: true
        prerelease: false
        release_name: v${{ env.LD_VERSION }}
        tag_name: v${{ env.LD_VERSION }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload-release-asset
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/zip
        asset_name: leetcode-editor-${{ env.LD_VERSION }}.zip
        asset_path: ./build/distributions/leetcode-editor-${{ env.LD_VERSION }}.zip
        upload_url: ${{ steps.create_release.outputs.upload_url }}
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
